### ISSUE TITLE
`$ref` unable to resolve after evolve

### ISSUE THREAD

**Issue by braingram** [python-jsonschema/jsonschema#1060]
In attempting to update [ASDF](https://github.com/asdf-format/asdf) to make it compatible with 4.18 I ran into either a bug or a misunderstanding about `evolve`.

For a schema like in the following example that contains a `$ref` to another portion of the schema. Validation succeeds (with a valid object) with no errors when the schema is directly provided to a `Draft4Validator`. However if a `Draft4Validator` is made with an empty schema then `evolve` called with schema containing the `$ref` a subsequent call to `validate` raises `jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/isanumber'`.

This has been tested both on 4.17.3 and 4.18.0a1 and both fail similarly (with the following error in 4.18.a1 `referencing.exceptions.PointerToNowhere: '/definitions/isanumber' does not exist within {}`).

```python
import jsonschema


schema = {
    "$ref" : "#/definitions/isanumber",
    "definitions": {
        "isanumber": {"type": "number"}
    }
}

validator = jsonschema.Draft4Validator(schema)
validator.validate(instance=1)  # no error

base_validator = jsonschema.Draft4Validator({})
validator = base_validator.evolve(schema=schema)
validator.validate(instance=1)  # raises jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/isanumber'
```

Is this a bug or am I misunderstanding how `evolve` should behave?

Thanks!

**Comment by Julian** [comment]
Hey @braingram -- so `evolve` could definitely use better docs, apologies that this isn't clear.

(In general it's meant for people who are implementing new keywords or dialects of JSON Schema, rather than simply using an existing dialect to validate instances, so I'll assume that's what you're doing in your real code).

Basically what's happening is that `#` as a JSON pointer refers to "the root document". When you call `evolve`, you're saying "I'm changing the schema we're validating with", but that doesn't implicitly imply changing the root document *unless* your schema is a subresource itself. In JSON Schema the way you indicate that is by having an `$id` key (at least in recent drafts. In draft 4 which it looks like you're using, it's spelled `id`).

If your schema has one of those, then it's a new subresource, and if you evolve into it, now `#` refers to the subresource.

So in summary, if we ignore evolve for a minute, in this schema:

```json
{
    "allOf": [{"$ref": "#/definitions/foo"}],
    "definitions": {
        "foo": {"type": "string"},
        "baz": {"$ref": "#/definitions/foo" },
        "bar": {
            "id": "bar",
            "allOf": [{"$ref": "#/definitions/foo"}],
            "definitions": {
                "foo": {"type": "integer"}
            }
        }
    }
}
```

The `#/definitions/foo` in `"baz"` refers to `        "foo": {"type": "string"},`, but the `#/definitions/foo` in `bar` refers to `{"type": "integer"}` because since `bar` has an `id` key, it's a new subresource, and that changes where `#` points to.

Now for evolve -- it means "I have a new schema as my base schema", but it does *not* implicitly indicate that your new schema is a new resource, that's only the case if it has an `id` key.

Does that help? Basically maybe you want to add an `id` key. (As I say, calling evolve on something that isn't somehow a sub-object of some parent object is slightly odd too, but occasionally it's what you want if you know that's the operation you want) 

the `#/definitions/foo` in the first property refers to

**Comment by braingram** [comment]
Thanks! I think I better understand the use for evolve now (changing the base schema). It will take me a bit to understand the implications of your answer (thanks for the details!).

I'll close the issue as this was my misunderstanding and not a bug.
