### ISSUE TITLE
Add possibility to set custom messages or use different languages

### ISSUE THREAD

**Issue by gloaguen-evan** [python-jsonschema/jsonschema#1101]
Hello,

I use jsonschema to validate features and I would like to be able to modify some error messages as well as to be able to offer messages in the user's language.

This is my first participation in a project and I saw that it was better to discuss in Issues before proposing a Pull Request, so here I am.

Here is my branch:
https://github.com/gloaguen-evan/jsonschema/tree/feat(messages)/add_possibility_to_set_custom_messages_and_translation

Thank you in advance for your attention regarding my request.

Evan

**Comment by Julian** [comment]
Hi there! Thanks a lot for your offer, it's very much appreciated.

There's an existing issue open at #971 -- let's move discussion there if that works.

Briefly, just scanning the branch, I think we'd want to do this using the [stdlib gettext module](https://docs.python.org/3/library/gettext.html) rather than rolling our own way of indicating messages. You did quite well though, especially if indeed this is your first contribution, so yeah well done! I suspect if you try wiring `gettext` in you may be able to mostly delete things rather than needing to make significant changes but hard to guess.

If you do do so, I will probably have limited time to review this for at least a month or two, there are a few other things on my plate that are higher priority (for the library). Don't take that as a slight I hope!

But if you're indeed interested it'd be very much appreciated, I'd love the help. Thanks again and props for the work so far.
