### ISSUE TITLE
Validating "slug" and deny line ending and the end.

### ISSUE THREAD

**Issue by jedie** [python-jsonschema/jsonschema#1148]
A "slug" regular expression can look like this: `r'^[-a-zA-Z0-9_]+\Z'`

But `\Z` can't be used in JSON schema, because the regular expression syntax used from JavaScript and they doesn't support `\Z`.
Other libraries like https://github.com/swaggest/php-json-schema has a check for this case, e.g.:
```
        if (substr($data, -2) === '\Z') {
            return 'Invalid regex: \Z is not supported';
        }
```
https://github.com/swaggest/php-json-schema/blob/2d7b8e22a9de2680b8639404502df0b24b834da6/src/Constraint/Format.php#L111-L113

This is missing in jsonschema.

If we replace `\Z` with `$` (e.g.: `r'^[-a-zA-Z0-9_]+\Z'`) then a string with line ending like `foo\n` is valid because jsonschema seems not use use `re.DOTALL`, isn't it?

Or did i miss something?

tl;td;

- `\Z` should not be accepted
- `re.DOTALL` should be used for regex

**Comment by jedie** [comment]
Yes, but one of our schema consumer is a PHP project ;) So we can't use `\Z` :(

**Comment by Julian** [comment]
I'm not sure what else to offer then, you need to pick a common subset of regex syntax that works for what you're using.

`\Z` is valid in Python, so there's no reason to disallow it, and `re.DOTALL` isn't the default in Python so there's no reason to enable it, but you're welcome to enable it inside your own regex if you want it on and your other consumers are OK with it.

Otherwise you might be interested in #1142 but that's something off in the future, and you'd still need to find a PHP regex implementation for Python or a JS implementation for PHP.

**Comment by jedie** [comment]
> you're welcome to enable it inside your own regex
Oh, is this possible? How?

**Comment by Julian** [comment]
See https://docs.python.org/3/library/re.html#regular-expression-syntax, specifically `(?s)` IIRC.

**Comment by jedie** [comment]
> See https://docs.python.org/3/library/re.html#regular-expression-syntax, specifically (?s) IIRC.

Oh, yes. So easy. Thanks!
