### ISSUE TITLE
Using the copy button of the code block in the README results in error "zsh: command not found: $"

### ISSUE THREAD

**Issue by activus-d** [python-jsonschema/jsonschema#1246]
## Description

When clicking the copy button from the block code in the README to install `jsonschema`, the copied text is `$ pip install jsonschema`. Running the copied command returns a "command not found: $" error. I believe this will be same for all other block codes in the README.

The possible solution is to modify the commands in the README.rst file to exclude the leading `$` symbol. For example:

```
.. code:: bash

    pip install jsonschema
```

**Comment by activus-d** [comment]
I can work on this issue if assigned.

**Comment by Julian** [comment]
Hi there! Thanks for the report. Showing a `$` there is pretty common in documentation, it's meant to indicate a shell prompt, and should be understood not to be copied -- it's arguably also good that it's there, as it's good practice not to copy+paste shell commands in the first place!

That all being said though, I've slightly tweaked the settings for `sphinx-copybutton` which is the plugin we use to show a "copy to clipboard" button in the [documentation](https://python-jsonschema.readthedocs.io/en/latest/), so that now at least if you use that, it's not included.

Appreciate the issue nonetheless.
