### ISSUE TITLE
Nested references are not loaded and the exception is unclear

### ISSUE THREAD

**Issue by traut** [python-jsonschema/jsonschema#209]
Test case (all files are in the same directory):

File `schema-a.json`

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema",

    "title": "schema A",
    "type": "object",
    "allOf": [
        {"$ref": "file:schema-b.json"}
    ]
}
```

File `schema-b.json`:

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema",

    "title": "schema B",
    "type": "object",
    "allOf": [
        {"$ref": "file:schema-c.json"}
    ]
}
```

File `schema-c.json`:

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema",

    "title": "schema C",
    "type": "object"
}
```

File `validate.py`:

``` python
import json
from os.path import dirname
from jsonschema import validate, RefResolver

with open('schema-a.json', 'r') as f:
    schema_a = json.loads(f.read())

try:
    validate({}, schema_a)
except Exception, e:
    print "1 failed: %s" % e

try:
    CURRENT_DIR = dirname(__file__)
    resolver = RefResolver(base_uri='file://' + CURRENT_DIR + '/', referrer=None)
    validate({}, schema_a, resolver=resolver)
except Exception, e:
    print "2 failed: %s" % e
```

Result:

``` bash
$ python validate.py
1 failed: <urlopen error [Errno 2] No such file or directory: '/schema-c.json'>
2 failed: <urlopen error [Errno 2] No such file or directory: '/schema-b.json'>
$
```

**Comment by traut** [comment]
my bad, if `CURRENT_DIR` is not empty (it was when I was testing my code) _and `base_uri` ends with `/`_, validation succeeds. 

So there are 2 issues still open for me:
— Is there a reason why `jsonschema` can't load the files in the same local directory without asking for specific `base_uri`? It seems like an easy feature to add and would save a lot of user's time during development.
— `RefResolver` behaviour should not be affected by trailing `/` in `base_uri`

**Comment by wadeaa** [comment]
This may be related to the above or may be down to my misunderstanding but I am hoping someone canoffer a little insight. 
With the following:

File parameter_value_obj.json:
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "description":"Unique identifier for the parameter.",
      "type": "string",
      "minLength": 1
    },
    "value": {
      "description":"List of values for the parameter.",
      "type": "array",
      "uniqueItems": true,
      "additionalItems": {
        "type": "number"
      },
      "minItems": 1
    }
  },
  "required": [
    "value",
    "id"
  ]
}



File results_run.json:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "parameters": {
      "description":"List of app_parameters values needed.",
      "type": "array",
      "uniqueItems": true,
      "additionalItems": {
        "type": "object",
        "$ref": "parameter_value_obj.json"
      }
    },
    "name": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "parameters",
    "name"
  ]
}


Code:

json_body = {"name": "6", "parameters": [{"wibble": 23}]}
schema_file = "/home/user/schemata/results_run.json"
schema_path = "/home/user/schemata/"

with open(schema_file, "r") as res_file:
    result_read = res_file.read().replace('\n', '')

try:
    json_schema = json.loads(result_read)
except ValueError as detail:
    logger.warning("ValueError loading schema: "+str(detail))

try:
    resolver = jsonschema.RefResolver('file://' + schema_path + '/', None)
    jsonschema.validate(json_body, json_schema, resolver=resolver)
except Exception, e:
    logger.warning("Validation Failed")


I get no exceptions thrown, the schema is accepted and the validation seemingly passes - But it shouldn't, as the object within the "parameters" array is clearly not of type parameter_value_obj. Is this likely to be because I am not properly resolving the referrenced file? Or is this a bug in validation?

**Comment by traut** [comment]
@wadeaa I recommend you to try not to reference `parameter_value_obj.json` directly, but put it in `definitions` block, like that - https://github.com/traut/taxii-json-schemas-draft/blob/master/schemas/message.json#L7 - and reference it with local path `#definitions/name`

this works nicely for me

**Comment by wadeaa** [comment]
Hi Traut, thanks. Yes that is the way I have it now, and it does work. But the documentation is growing and I want to be able to reuse certain objects in multiple schema. It would make sense to be able to only define them (and also update them) once in their own files. 

I just can't see how it can be properly loading the reference if it is passing validation, but then I am not getting any SchemaError either. I will keep playing with it.

**Comment by traut** [comment]
@wadeaa if you look around in that repo I referenced, you'll see that I'm reusing some primitives there, referencing them in different (bigger) schemas

**Comment by gregbillock** [comment]
@traut This looks like the same issue I'm having in  #274 . Could you give a bit more detail about setting the CURRENT_DIR variable and base_uri, and corresponding workarounds for specifying the $ref: file:... values in nested schemas?

**Comment by traut** [comment]
@gregbillock [python code](https://github.com/Intelworks/TAXII-JSON-schemas/blob/master/validate.py#L30) and [example $ref](https://github.com/Intelworks/TAXII-JSON-schemas/blob/master/schemas/discovery-request.json#L8)

**Comment by gregbillock** [comment]
Thanks @traut. I was diving into the code to see if I needed a resolver subclass to get the job done, but this works well for what I'm doing right now. Thanks!

**Comment by Julian** [comment]
Looking back at this (after ages, apologies), but

>  — RefResolver behaviour should not be affected by trailing / in base_uri

This is the same as https://github.com/python-jsonschema/jsonschema/issues/274#issuecomment-1195387858 and the other duplicates mentioned there -- essentially that's just how relative URIs work, this library is just following the RFC (3986 in this case), but it's similar behavior to what you're all going to be used to from a browser.

There's really 2 options:

* remember to use a trailing slash, as you did ultimately
* always use a file as your base URI (e.g. one of your schemas) rather than a directory
