### ISSUE TITLE
CLI parameter for $ref

### ISSUE THREAD

**Issue by petsuter** [python-jsonschema/jsonschema#241]
Is it possible to use the CLI tool to validate a JSON file with a specific $ref into a schema file?

For example like: `jsonschema -i example.json -r #/definitions/example schema.json`

**Comment by petsuter** [comment]
Adding something like this to `cli.py` seems to work:
```python
parser.add_argument(
    "-R", "--ref",
    help="a reference into the JSON Schema",
)

#...
    if arguments["ref"]:
        schema = json.loads("""{ "$ref": "/schema.json#%s" }""" % arguments["ref"])
        validator = validator_for(schema)(schema=schema)
        validator.resolver.store['/schema.json'] = arguments["schema"]
    else:
        validator = arguments["validator"](schema=arguments["schema"])
#...
```

Is that a good idea or completly the wrong approach?

**Comment by Julian** [comment]
Hey! So sorry that I missed this.

It seems from the fact that I've heard this request a few times before that people would find it useful.

I'd prefer over what you have there though that we better expose generic resolution of JSON refs -- it should be possible to just resolve the ref from the CLI argument against the instance directly rather than needing a validator to do so.

If you still were interested in taking a shot at that I think it'd be reasonable. Sorry again that this went under my radar.

**Comment by Julian** [comment]
Another thing to consider: should it be possible to specify a ref for both the instance and the schema? If so, maybe the arguments should just be actual URIs with optional ref, rather than just file paths.

**Comment by petsuter** [comment]
Hi, thanks for your replies. Unfortunately I don't have any time to look into this more at the moment.

Also, I'm not really clear on what you mean. Would you change the command line invocation, the implementation of the command line option handling or completely change the library internals / API? Thanks

**Comment by Julian** [comment]
Superceded by [check-jsonschema](https://github.com/python-jsonschema/check-jsonschema) which is now the official (and more-featureful) CLI. Anyone interested in this is invited to have a look there (and file any issues necessary).
