### ISSUE TITLE
Problems with the example in docs/faq.rst

### ISSUE THREAD

**Issue by mpnowacki** [python-jsonschema/jsonschema#367]
I've encountered three issues when using the example supporting defaults (on python 3.5.3).
- the method `check_schema` crashes in a most peculiar way. Calling `DefaultValidatingDraft4Validator.check_schema(schema)` causes a `RecursionError: maximum recursion depth exceeded while calling a Python object`
- this code may work in an unexpected way when the `default` value is a mutable object. For example, let's say you validate an object and the default value gets injected. If you then manipulate this object, and modify the injected default value, the next time this schema injects the default value it shall be modified. Changing `instance.setdefault(property, subschema["default"])` to `instance.setdefault(property, copy.deepcopy(subschema["default"]))` solves this completely, maybe it's worth to include it in the example?
- This code doesn't work with python 3 because of the `.iteritems()` call, but that's just a cosmetic detail.

**Comment by Julian** [comment]
Hey! Thanks for the report.

Happy to fix these -- would you be able to send a PR?

For the second one, I'd not really like to promote the use of `copy.deepcopy`. Personally I'd not really recommend mutating objects :) -- Seep is/was a POC for how to do this in a way that I *would* recommend.

**Comment by jamesstidard** [comment]
Hi,

I've also been playing around with this example in the FAQ. I also found that both the `subschema` and `instance` values could be `boolean` values. For example, this happens when iterating the `readOnly` property.

Here's what I've ended up with:

```python
from copy import deepcopy
from jsonschema import Draft7Validator, validators


def extend_with_default(validator_class):
    validate_properties = validator_class.VALIDATORS["properties"]

    def set_defaults(validator, properties, instance, schema):
        for property_, subschema in properties.items():

            defaultable = (
                isinstance(subschema, dict) and
                isinstance(instance, dict) and
                "default" in subschema
            )

            if defaultable:
                default = deepcopy(subschema["default"])
                instance.setdefault(property_, default)

        for error in validate_properties(
            validator, properties, instance, schema,
        ):
            yield error

    return validators.extend(
        validator_class, {"properties": set_defaults},
    )


DefaultValidatingDraft7Validator = extend_with_default(Draft7Validator)
```

`jsonschema` is still new to me, so I don't know if this is robust or correct. Would appreciate a sanity check.

Here's what I used as an input schema:

```json
{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "example_schema",
      "default": "example_schema"
    },
    "price": {
      "type": "number",
      "default": 5
    },
    "name": {
      "type": "string",
      "default": "something"
    }
  },
  "default": {}
}
```

**Comment by akshenk8** [comment]
I just stumbled upon this issue. And, I'm quite new to this library. Forgive me if my questions turnout naive.

Is it possible to convert `VALIDATORS` to an `OrderedDict` instead of the current `Dict`, and iterate over `VALIDATORS` instead of [_schema.items()](https://github.com/Julian/jsonschema/blob/e48d56cbd2b6c25d4a9483f53f79ec537b9a4a34/jsonschema/validators.py#L309) ?
This won't solve the issue for the nested, but will guarantee an order of `VALIDATORS` execution.

**Comment by Julian** [comment]
PRs to improve the example code are definitely welcome here, but I'm going to close this since it's not really "fully supported" code, they're more like samples to start with. I don't see myself being able to dedicate much more time on them, but yeah help is welcome, as is someone creating an external library containing them built on top of this library so others can contribute.
