### ISSUE TITLE
Support for other file formats in the CLI

### ISSUE THREAD

**Issue by nightwatchcyber** [python-jsonschema/jsonschema#582]
Would you consider adding support for validating other file formats (YAML, TOML, INI, etc) via JSON Schema? This would be similar to the functionality provided by this NodeJS project:
https://github.com/json-schema-everywhere/pajv

It is possible to add this functionality via the "anymarkup" module:
https://github.com/bkabrda/anymarkup

I can provide a pull request with these changes

**Comment by Julian** [comment]
Hi! Thanks for the idea and offer --

So, I do this personally with [remarshal](https://github.com/dbohdan/remarshal).

E.g. by running `jsonschema -i <(yml2json schema.yml) etc`

I am... not completely against having that more native (though yeah for me what I do already works quite OK), but I have reservations about "magic". It's easy (as anymarkup says itself) to have ambiguous say INI vs TOML, so it's introducing room for complexity and incorrectness there.

Happy to hear your thoughts on that if you have any.

**Comment by thebjorn** [comment]
(not OP) I would be happy to have this for only yaml to start with since it doesn't introduce ambiguity, schemas are much nicer to write in yaml (and our own config files are in yaml and needs validation). Since yaml is a subset of json there shouldn't be much, if any, magic need :-)

remarshal is a great tool, but your example is not quite so convenient on windows (or when both schema and instance are yaml).

**Comment by Julian** [comment]
That all makes sense to me! Definitely OK with that much.

**Comment by ssbarnea** [comment]
@julesjulian I was looking to create a YAML linter that would use data from http://schemastore.org/json/ (which applies to yaml too) but without having native support for yaml I am kinda stuck.

Once this is covered, I can start implementing the tool which should be able to detect schema to use, use internal cache of schemas, lint all files from a repo. If you think that this could be desirable for your tool, I don't mind extending it, otherwise I would make another tool that only calls jsonschema for validating the these files.

**Comment by Julian** [comment]
@ssbarnea that's.. interesting, I don't think I'd seen that before.

I think I'm not opposed to adding support for that if it's reasonably small to implement.

Can we tackle that separately though? I.e., one ticket (this one) for just switching to parsing via YAML, and a second one for adding support for schema store to the CLI?

**Comment by gsemet** [comment]
I would be interested in having a transparent yaml loader with $ref resolution. It would require to restrict to the YAML syntax that is 1:1 transposable to json.

**Comment by ssbarnea** [comment]
I think that for start trying using the pyyaml loader when file extension is either `.yml` or `.yaml` should count as easy and safe to implement.

We could even make the dependency on pyyaml soft and enable the feature only when it is installed.

**Comment by ioggstream** [comment]
While I'm not sure of the "anymarkup", given that YAML is widely used when developing json-schema and OpenAPI3 files, even a simple YAML loader (eg. yaml.safe_load) would be great. 

I think that a conservative solution could even rely on  a specify CLI parameter (eg. --yaml) that will do something like

```
jsonschema/cli.py

class Outputter():
   def from_arguments(...):
      if ... yaml in arguments ... :
            ... set loader ...
      
...
def run(...):

   schema_loader = json.load
   if ... yaml in arguments ... :
       schema_loader = yaml.safe_load

```

Probably a way to specify the loader in a single place could work too (eg. outputter.schema_loader )

If you are interested, I'm happy to PR :)

**Comment by sirosen** [comment]
Providing this feature is one of the main goals for `check-jsonschema`.

It provides `json` and `yaml` support by default, and if `pyjson5` or `json5` is installed, it will support JSON5 format files as well. If TOML is really wanted, I'd probably add `tomli` support following the same path laid out by JSON5. I'm less enthusiastic about INI support (though configparser makes it easy), but could be convinced if users really want it.

YAML for schema files is only supported for local files. Because a RefResolver won't understand YAML, it didn't seem very safe to try to load remote schemas as YAML. I'm happy to revisit or discuss this behavior.

I'd love to hear from any of the users in this thread if `check-jsonschema` does (or does not!) meet their needs.

_I am the author of `check-jsonschema` and we are currently discussing making it the official CLI for `jsonschema`. For details, you can follow #910. If `check-jsonschema` has a behavior which you believe should be changed to handle your use-case, please [open an issue](https://github.com/sirosen/check-jsonschema/issues/new)!_

**Comment by sirosen** [comment]
We're going to move forward and begin calling `check-jsonschema` the official CLI. I'm therefore going to close this as a wontfix.
