### ISSUE TITLE
Support specifying a base URI explicitly to the CLI

### ISSUE THREAD

**Issue by koteez** [python-jsonschema/jsonschema#669]
Hi,

I have a json schema that depends on other files that are located in the same directory. Running the CLI I got an issue because the resolver is trying to load the file from the same URI as my main script. As I am working locally I didn't have a server serving the schemas and thus the resolution fails. 

```
{
 "ArrayA":{
    "type": "array",
     "items": {
	  "$ref": "common.json#/definitions/ObjectB"
      }
   }
} 
```
Using __file:__ require to put the absolute path which is a non-sense inside the schema definition.
What could be intesting to do is having a parameter to the CLI so that we can override the base_uri with $PWD value which will work.

Thanks & regards

K

**Comment by sirosen** [comment]
I believe -- I'm not totally certain -- that the local file resolution behavior used in `check-jsonschema` would fit this.
When a local schemafile is used, it sets the resolver to use a base-ref pointed at the filename.

I'm aware this issue is pretty old, but I'd love to hear from the OP if this works.

_I am the author of `check-jsonschema` and we are currently discussing making it the official CLI for `jsonschema`. For details, you can follow #910. If `check-jsonschema` has a behavior which you believe should be changed to handle your use-case, please [open an issue](https://github.com/sirosen/check-jsonschema/issues/new)!_

**Comment by sirosen** [comment]
We're going to move forward and begin calling `check-jsonschema` the official CLI. I'm therefore closing this as a wontfix. I _believe_ that the behavior in `check-jsonschema` is sufficient. If not, I'm happy to take a bug report on that repo.
