### ISSUE TITLE
RefResolver breaks directories passed as base_uri

### ISSUE THREAD

**Issue by reitzig** [python-jsonschema/jsonschema#915]
I create a validator like so (Python 3.8.10, jsonschema 4.4.0):

```python
# schema_file: pathlib.Path
schema = json.loads(schema_file.read_text())
ref_resolver = jsonschema.RefResolver(base_uri=schema_file.parent.absolute().as_uri(), None)
validator_class = jsonschema.validators.validator_for(schema)
validator_class.check_schema(schema)  # just to be sure; treat as bug --> no error handling!
return validator_class(schema, resolver=ref_resolver)
```

I **expect** this to work in the sense that 

`stuff.schema.json`
```
"$ref": "definitions.schema.json#/definitions/id"
```

resolves during validation, provided `stuff.schema.json` and `definitions.schema.json` reside in the same directory.

What **actually** happens is that the last directory is stripped.

[MWE](https://gist.github.com/reitzig/383509b990c5547be47e8767fe021381) (the failing case for `example_mod.schema.json`)

**Proposal:** Remove the auto-stripping behaviour, or only strip if the last path component is a file (i.e. not a directory).

**Workarounds**:

Use either of these as `base_uri`:

 - `schema_file.absolute().as_uri()` (counter-intuitive; relies on `jsonschema` performing the equivalent of `parent`)
 - `f"{schema_file.parent.absolute().as_uri()}/"` (seems unnecessary)

**Comment by Julian** [comment]
There's still a bit too much in these MWEs to immediately see what's wrong, so it'll have to wait until I have some more cycles -- just on 

> f"{schema_file.parent.absolute().as_uri()}/" (seems unnecessary)

whether `something://foo` and `something://foo/` are the same URI depends on the scheme IIRC. So this is not something `jsonschema` can do for you in the general case, it's indeed necessary if you want the latter to be your base URI.

**Comment by Julian** [comment]
Looking back at this,

> What actually happens is that the last directory is stripped.

This is simply the behavior defined by relative URIs. It's the same as if you have `http://foo.com/bar` on a website, and put `<a href="foo/">` in your HTML, you get `http://foo.com/foo`, not `http://foo.com/bar/foo`.

This library doesn't deal with path normalization, that's entirely `pathlib` doing it, so the correct thing to do is as you mentioned, ensure your base URI has a trailing slash by using `f"{path.as_uri()}/"` instead of just `path.as_uri()`.

Alternatively, have your base URI be a file within the directory, not the directory itself.
